import Swal from 'sweetalert2';

export const showError = (message, footer = '') => {
  return Swal.fire({
    title: 'Error!',
    html: message,
    icon: 'error',
    confirmButtonColor: 'gray',
    footer: footer ? `<a href="#">${footer}</a>` : ''
  });
};

export const showSuccess = (message) => {
  return Swal.fire({
    title: 'Success!',
    html: message,
    icon: 'success',
    confirmButtonColor: 'gray'
  });
};

export const showPlaylistCreationDialog = async (onCreate) => {
  return Swal.fire({
    title: "Create New Playlist",
    html: `
      <div style="margin-top: 10px;">
        <label>
          Playlist Name
          <input type="text" id="playlist-name" class="swal2-input" placeholder="Minion Playlist" value="Minion Playlist">
        </label>
      </div>
      <div style="margin-top: 10px;">
        <label>
          Playlist Description
          <input id="playlist-description" class="swal2-input" placeholder="Generated with Minion" value="Generated with Minion">
        </label>
      </div>
      <div style="text-align: left; margin-top: 10px;">
        <label for="playlist-public">
          <input type="checkbox" id="playlist-public" style="margin-right: 10px;">
          Make playlist public
        </label>
      </div>
    `,
    confirmButtonText: "Create",
    confirmButtonColor: "green",
    focusConfirm: false,
    background: "gray",
    color: "white",
    customClass: {
      title: "custom-swal-title",
    },
    preConfirm: () => {
      const name = document.getElementById("playlist-name").value.trim();
      let description = document.getElementById("playlist-description").value.trim();
      const isPublic = document.getElementById("playlist-public").checked;

      if (!name) {
        Swal.showValidationMessage("Playlist name is required.");
        return false;
      }
      
      if (!description) {
        description = "Generated by Spotify App";
      }

      return { name, description, isPublic };
    }
  }).then((result) => {
    if (result.isConfirmed && onCreate) {
      onCreate(result.value);
    }
    return result;
  });
};